### ISSUE TITLE
android studio 版本问题

### ISSUE THREAD

**Issue by HarrisonShen** [HaowenLee/ReaderT#1]
classpath 'com.haowen.huge:huge-plugin:1.0.0'这个是不是一定要5.1.1版本 有没有低版本的

**Comment by HaowenLee** [comment]
> classpath 'com.haowen.huge:huge-plugin:1.0.0'这个是不是一定要5.1.1版本 有没有低版本的

这是一个调试用的，我注释掉了，你再试试
