### ISSUE TITLE
app报错

### ISSUE THREAD

**Issue by HarrisonShen** [HaowenLee/ReaderT#2]
Error:A problem occurred configuring project ':fBReader'.  这个是什么原因

**Comment by HaowenLee** [comment]
能提供一下更详细的信息么？ndk-bundle路径配置正确么？

**Comment by HaowenLee** [comment]
> Error:A problem occurred configuring project ':fBReader'. 这个是什么原因

能提供一下更详细的信息么？ndk-bundle路径配置正确么？
